//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string NAT { get; set; }
        public Nullable<int> OA { get; set; }
        public Nullable<int> LEA { get; set; }
        public Nullable<int> MEC { get; set; }
        public Nullable<int> ELE { get; set; }
        public Nullable<int> AER { get; set; }
        public Nullable<int> EXP { get; set; }
        public Nullable<int> PIT { get; set; }
        public Nullable<int> MOT { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> RET { get; set; }
        public Nullable<int> SAL { get; set; }
        public Nullable<int> FEE { get; set; }
        public Nullable<int> OFF { get; set; }
        public Nullable<System.DateTime> Last_updated { get; set; }
        public Nullable<bool> Ativo { get; set; }
    }
}
