//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WindowsFormsApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Drivers> Drivers
        {
            get
            {
                if ((_Drivers == null))
                {
                    _Drivers = base.CreateObjectSet<Drivers>("Drivers");
                }
                return _Drivers;
            }
        }
        private ObjectSet<Drivers> _Drivers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TD> TD
        {
            get
            {
                if ((_TD == null))
                {
                    _TD = base.CreateObjectSet<TD>("TD");
                }
                return _TD;
            }
        }
        private ObjectSet<TD> _TD;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Drivers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDrivers(Drivers drivers)
        {
            base.AddObject("Drivers", drivers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TD EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTD(TD tD)
        {
            base.AddObject("TD", tD);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gameModel", Name="Drivers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Drivers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Drivers object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Drivers CreateDrivers(global::System.Int32 id)
        {
            Drivers drivers = new Drivers();
            drivers.ID = id;
            return drivers;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAT
        {
            get
            {
                return _NAT;
            }
            set
            {
                OnNATChanging(value);
                ReportPropertyChanging("NAT");
                _NAT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAT");
                OnNATChanged();
            }
        }
        private global::System.String _NAT;
        partial void OnNATChanging(global::System.String value);
        partial void OnNATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OA
        {
            get
            {
                return _OA;
            }
            set
            {
                OnOAChanging(value);
                ReportPropertyChanging("OA");
                _OA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OA");
                OnOAChanged();
            }
        }
        private Nullable<global::System.Int32> _OA;
        partial void OnOAChanging(Nullable<global::System.Int32> value);
        partial void OnOAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CON
        {
            get
            {
                return _CON;
            }
            set
            {
                OnCONChanging(value);
                ReportPropertyChanging("CON");
                _CON = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CON");
                OnCONChanged();
            }
        }
        private Nullable<global::System.Int32> _CON;
        partial void OnCONChanging(Nullable<global::System.Int32> value);
        partial void OnCONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TAL
        {
            get
            {
                return _TAL;
            }
            set
            {
                OnTALChanging(value);
                ReportPropertyChanging("TAL");
                _TAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAL");
                OnTALChanged();
            }
        }
        private Nullable<global::System.Int32> _TAL;
        partial void OnTALChanging(Nullable<global::System.Int32> value);
        partial void OnTALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EXP
        {
            get
            {
                return _EXP;
            }
            set
            {
                OnEXPChanging(value);
                ReportPropertyChanging("EXP");
                _EXP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EXP");
                OnEXPChanged();
            }
        }
        private Nullable<global::System.Int32> _EXP;
        partial void OnEXPChanging(Nullable<global::System.Int32> value);
        partial void OnEXPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AGG
        {
            get
            {
                return _AGG;
            }
            set
            {
                OnAGGChanging(value);
                ReportPropertyChanging("AGG");
                _AGG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AGG");
                OnAGGChanged();
            }
        }
        private Nullable<global::System.Int32> _AGG;
        partial void OnAGGChanging(Nullable<global::System.Int32> value);
        partial void OnAGGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TEI
        {
            get
            {
                return _TEI;
            }
            set
            {
                OnTEIChanging(value);
                ReportPropertyChanging("TEI");
                _TEI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TEI");
                OnTEIChanged();
            }
        }
        private Nullable<global::System.Int32> _TEI;
        partial void OnTEIChanging(Nullable<global::System.Int32> value);
        partial void OnTEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> STA
        {
            get
            {
                return _STA;
            }
            set
            {
                OnSTAChanging(value);
                ReportPropertyChanging("STA");
                _STA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STA");
                OnSTAChanged();
            }
        }
        private Nullable<global::System.Int32> _STA;
        partial void OnSTAChanging(Nullable<global::System.Int32> value);
        partial void OnSTAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CHA
        {
            get
            {
                return _CHA;
            }
            set
            {
                OnCHAChanging(value);
                ReportPropertyChanging("CHA");
                _CHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHA");
                OnCHAChanged();
            }
        }
        private Nullable<global::System.Int32> _CHA;
        partial void OnCHAChanging(Nullable<global::System.Int32> value);
        partial void OnCHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MOT
        {
            get
            {
                return _MOT;
            }
            set
            {
                OnMOTChanging(value);
                ReportPropertyChanging("MOT");
                _MOT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MOT");
                OnMOTChanged();
            }
        }
        private Nullable<global::System.Int32> _MOT;
        partial void OnMOTChanging(Nullable<global::System.Int32> value);
        partial void OnMOTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> REP
        {
            get
            {
                return _REP;
            }
            set
            {
                OnREPChanging(value);
                ReportPropertyChanging("REP");
                _REP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("REP");
                OnREPChanged();
            }
        }
        private Nullable<global::System.Int32> _REP;
        partial void OnREPChanging(Nullable<global::System.Int32> value);
        partial void OnREPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AGE
        {
            get
            {
                return _AGE;
            }
            set
            {
                OnAGEChanging(value);
                ReportPropertyChanging("AGE");
                _AGE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AGE");
                OnAGEChanged();
            }
        }
        private Nullable<global::System.Int32> _AGE;
        partial void OnAGEChanging(Nullable<global::System.Int32> value);
        partial void OnAGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WEI
        {
            get
            {
                return _WEI;
            }
            set
            {
                OnWEIChanging(value);
                ReportPropertyChanging("WEI");
                _WEI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WEI");
                OnWEIChanged();
            }
        }
        private Nullable<global::System.Int32> _WEI;
        partial void OnWEIChanging(Nullable<global::System.Int32> value);
        partial void OnWEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RET
        {
            get
            {
                return _RET;
            }
            set
            {
                OnRETChanging(value);
                ReportPropertyChanging("RET");
                _RET = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RET");
                OnRETChanged();
            }
        }
        private Nullable<global::System.Int32> _RET;
        partial void OnRETChanging(Nullable<global::System.Int32> value);
        partial void OnRETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SAL
        {
            get
            {
                return _SAL;
            }
            set
            {
                OnSALChanging(value);
                ReportPropertyChanging("SAL");
                _SAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SAL");
                OnSALChanged();
            }
        }
        private Nullable<global::System.Int32> _SAL;
        partial void OnSALChanging(Nullable<global::System.Int32> value);
        partial void OnSALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FEE
        {
            get
            {
                return _FEE;
            }
            set
            {
                OnFEEChanging(value);
                ReportPropertyChanging("FEE");
                _FEE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FEE");
                OnFEEChanged();
            }
        }
        private Nullable<global::System.Int32> _FEE;
        partial void OnFEEChanging(Nullable<global::System.Int32> value);
        partial void OnFEEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OFF
        {
            get
            {
                return _OFF;
            }
            set
            {
                OnOFFChanging(value);
                ReportPropertyChanging("OFF");
                _OFF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OFF");
                OnOFFChanged();
            }
        }
        private Nullable<global::System.Int32> _OFF;
        partial void OnOFFChanging(Nullable<global::System.Int32> value);
        partial void OnOFFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Last_updated
        {
            get
            {
                return _Last_updated;
            }
            set
            {
                OnLast_updatedChanging(value);
                ReportPropertyChanging("Last_updated");
                _Last_updated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Last_updated");
                OnLast_updatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Last_updated;
        partial void OnLast_updatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLast_updatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Ativo;
        partial void OnAtivoChanging(Nullable<global::System.Boolean> value);
        partial void OnAtivoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gameModel", Name="TD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TD object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TD CreateTD(global::System.Int32 id)
        {
            TD tD = new TD();
            tD.ID = id;
            return tD;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAT
        {
            get
            {
                return _NAT;
            }
            set
            {
                OnNATChanging(value);
                ReportPropertyChanging("NAT");
                _NAT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAT");
                OnNATChanged();
            }
        }
        private global::System.String _NAT;
        partial void OnNATChanging(global::System.String value);
        partial void OnNATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OA
        {
            get
            {
                return _OA;
            }
            set
            {
                OnOAChanging(value);
                ReportPropertyChanging("OA");
                _OA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OA");
                OnOAChanged();
            }
        }
        private Nullable<global::System.Int32> _OA;
        partial void OnOAChanging(Nullable<global::System.Int32> value);
        partial void OnOAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LEA
        {
            get
            {
                return _LEA;
            }
            set
            {
                OnLEAChanging(value);
                ReportPropertyChanging("LEA");
                _LEA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LEA");
                OnLEAChanged();
            }
        }
        private Nullable<global::System.Int32> _LEA;
        partial void OnLEAChanging(Nullable<global::System.Int32> value);
        partial void OnLEAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MEC
        {
            get
            {
                return _MEC;
            }
            set
            {
                OnMECChanging(value);
                ReportPropertyChanging("MEC");
                _MEC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MEC");
                OnMECChanged();
            }
        }
        private Nullable<global::System.Int32> _MEC;
        partial void OnMECChanging(Nullable<global::System.Int32> value);
        partial void OnMECChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ELE
        {
            get
            {
                return _ELE;
            }
            set
            {
                OnELEChanging(value);
                ReportPropertyChanging("ELE");
                _ELE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ELE");
                OnELEChanged();
            }
        }
        private Nullable<global::System.Int32> _ELE;
        partial void OnELEChanging(Nullable<global::System.Int32> value);
        partial void OnELEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AER
        {
            get
            {
                return _AER;
            }
            set
            {
                OnAERChanging(value);
                ReportPropertyChanging("AER");
                _AER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AER");
                OnAERChanged();
            }
        }
        private Nullable<global::System.Int32> _AER;
        partial void OnAERChanging(Nullable<global::System.Int32> value);
        partial void OnAERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EXP
        {
            get
            {
                return _EXP;
            }
            set
            {
                OnEXPChanging(value);
                ReportPropertyChanging("EXP");
                _EXP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EXP");
                OnEXPChanged();
            }
        }
        private Nullable<global::System.Int32> _EXP;
        partial void OnEXPChanging(Nullable<global::System.Int32> value);
        partial void OnEXPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PIT
        {
            get
            {
                return _PIT;
            }
            set
            {
                OnPITChanging(value);
                ReportPropertyChanging("PIT");
                _PIT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PIT");
                OnPITChanged();
            }
        }
        private Nullable<global::System.Int32> _PIT;
        partial void OnPITChanging(Nullable<global::System.Int32> value);
        partial void OnPITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MOT
        {
            get
            {
                return _MOT;
            }
            set
            {
                OnMOTChanging(value);
                ReportPropertyChanging("MOT");
                _MOT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MOT");
                OnMOTChanged();
            }
        }
        private Nullable<global::System.Int32> _MOT;
        partial void OnMOTChanging(Nullable<global::System.Int32> value);
        partial void OnMOTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AGE
        {
            get
            {
                return _AGE;
            }
            set
            {
                OnAGEChanging(value);
                ReportPropertyChanging("AGE");
                _AGE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AGE");
                OnAGEChanged();
            }
        }
        private Nullable<global::System.Int32> _AGE;
        partial void OnAGEChanging(Nullable<global::System.Int32> value);
        partial void OnAGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RET
        {
            get
            {
                return _RET;
            }
            set
            {
                OnRETChanging(value);
                ReportPropertyChanging("RET");
                _RET = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RET");
                OnRETChanged();
            }
        }
        private Nullable<global::System.Int32> _RET;
        partial void OnRETChanging(Nullable<global::System.Int32> value);
        partial void OnRETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SAL
        {
            get
            {
                return _SAL;
            }
            set
            {
                OnSALChanging(value);
                ReportPropertyChanging("SAL");
                _SAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SAL");
                OnSALChanged();
            }
        }
        private Nullable<global::System.Int32> _SAL;
        partial void OnSALChanging(Nullable<global::System.Int32> value);
        partial void OnSALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FEE
        {
            get
            {
                return _FEE;
            }
            set
            {
                OnFEEChanging(value);
                ReportPropertyChanging("FEE");
                _FEE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FEE");
                OnFEEChanged();
            }
        }
        private Nullable<global::System.Int32> _FEE;
        partial void OnFEEChanging(Nullable<global::System.Int32> value);
        partial void OnFEEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OFF
        {
            get
            {
                return _OFF;
            }
            set
            {
                OnOFFChanging(value);
                ReportPropertyChanging("OFF");
                _OFF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OFF");
                OnOFFChanged();
            }
        }
        private Nullable<global::System.Int32> _OFF;
        partial void OnOFFChanging(Nullable<global::System.Int32> value);
        partial void OnOFFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Last_updated
        {
            get
            {
                return _Last_updated;
            }
            set
            {
                OnLast_updatedChanging(value);
                ReportPropertyChanging("Last_updated");
                _Last_updated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Last_updated");
                OnLast_updatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Last_updated;
        partial void OnLast_updatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLast_updatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Ativo;
        partial void OnAtivoChanging(Nullable<global::System.Boolean> value);
        partial void OnAtivoChanged();

        #endregion

    
    }

    #endregion

    
}
